version: "3.8"
services:
  memcached:
    image: memcached:alpine
    container_name: memcached
    restart: always
    ports:
      - 9059:11211
    networks:
      - memcached-net
    volumes:
      - memcached-data:/data

networks:
  memcached-net:
    driver: bridge
volumes:
  memcached-data:
