version: "3.8"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports: 
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml