version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - 8079:2181
  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9653:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:8079
      KAFKA_CREATE_TOPICS: ["first_topic:1:1", "second_topic:1:1"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
