version: "3.8"

services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
          - 7115:5432
        environment:
            POSTGRES_PASSWORD: pg
            POSTGRES_USER: pg
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 8449:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres

volumes:
    postgres:
    pgadmin:
